### ISSUE TITLE
Generate the OpenAPI specification from the file "common-schema.json"

### ISSUE THREAD

**Issue by a39172** [smart-data-models/data-models#43]
I want to extend the base models using Swagger - `$ref` - and at the moment there seems to be no OpenAPI specification of `common-schema.json`. If you use the JSON file it works but it is not recommended - schema must be of a [Schema Object](https://swagger.io/specification/#schema-object) and not a standard JSON Schema - and the output is different.

In my case I am extending the model representing an "Organization" with a "ContactPoint" and, in the absence of `common-schema.yaml`, I am using the `schema.org.yaml` file:

```
components:
  schemas:
    Company:
      type: object
      allOf:
        - $ref: "https://smart-data-models.github.io/dataModel.Organization/Organization/model.yaml#/Organization"
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/ContactPoint"
      required:
        - "name"
        - "address"
        - "location"
        - "taxID"
        - "email"
```

**Comment by a39172** [comment]
I add another situation where I had to manually and unnecessarily set the "EntityIdentifierType" when I could use the same definition from the `common-schema`:
```
Client:
      type: object
      allOf:
        - $ref: "https://smart-data-models.github.io/dataModel.Organization/Organization/model.yaml#/Organization"
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/ContactPoint"
      properties:
        provider:
          description: "Relationship. Organization from which the system was acquired."
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: "Property. Identifier format of any NGSI entity"
              format: uri
              type: string
          x-ngsi:
            model: https://schema.org/URL
            type: Relationship
      # Required properties in addition to those already defined required in the referenced schemas.
      required:
        - "name"
        - "address"
        - "location"
        - "taxID"
        - "email"
        - "provider"
```
